ALTER TABLE api_keys ADD COLUMN model TEXT NOT NULL DEFAULT 'gemini';
ALTER TABLE api_keys ADD COLUMN rpm_limit INTEGER NOT NULL DEFAULT 15;
ALTER TABLE api_keys ADD COLUMN tpm_limit INTEGER NOT NULL DEFAULT 1000000;
ALTER TABLE api_keys ADD COLUMN rpd_limit INTEGER NOT NULL DEFAULT 1500;
